#!/bin/bash
# starexec_build.sh, Norbert Manthey, 2019
#
# build MergeSAT, and SparrowToMergeSAT in case the package contains the dependencies

set -x

# let's use a more recent toolchain
scl enable devtoolset-7 bash || true

#make minisat
pushd minisat

# by now, we need a "minisat" link to build
ln -s . minisat || true

# build
make 2>&1

# provide build artifact to starexec
cp build/release/bin/mergesat ../bin/
popd

# For Sparrow2MergeSAT, we need Sparrow, as well as Coprocessor

# in case we have the Sparrow package, build it as well
if [ -d Sparrow ]
then
	# build Sparrow
	pushd Sparrow
	unzip Sparrow.zip
	make -j $(nproc)
	popd

	# make sparrow binary available to starexec
	cp Sparrow/sparrow bin/
fi

# in case we have the Riss package, build it as well
if [ -d Riss ]
then
	# build Sparrow
	pushd Riss
	unzip Riss.zip
	./starexec_build
	popd

	# make coprocessor binary available to starexec
	cp Riss/bin/coprocessor bin/
fi
