name: Check code style

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install zlib1g-dev make cmake clang-format-6.0

    - uses: actions/checkout@v1

    - name: mergesat build
      run: ./tools/check-style.sh
